make BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT USER_C_MODULES=../../../modules CFLAGS_EXTRA=-DHAVE_CONFIG_H=1 all

# make BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT clean

make BOARD=ESP32_GENERIC_P4 BOARD_VARIANT=C6_WIFI USER_C_MODULES=../../../modules/p4_modules.cmake CFLAGS_EXTRA=-DHAVE_CONFIG_H=1 all

# make BOARD=ESP32_GENERIC_P4 BOARD_VARIANT=C6_WIFI clean