# Select the minimum chip revision to cover all possible boards.
CONFIG_ESP32P4_REV_MIN_0=y

# Flash
CONFIG_FLASHMODE_QIO=y
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions-16MiB-custom.csv"

# Memory
CONFIG_SPIRAM=y
CONFIG_SPIRAM_MEMTEST=
CONFIG_SPIRAM_IGNORE_NOTFOUND=y
CONFIG_MBEDTLS_DEFAULT_MEM_ALLOC=y
CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=50768

# ULP: not fixed
CONFIG_SOC_ULP_SUPPORTED=n
CONFIG_ULP_COPROC_ENABLED=n
CONFIG_ULP_COPROC_TYPE_FSM=n

CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=y

# Camera sensor: OV5647 via MIPI CSI
CONFIG_CAMERA_OV5647=y
CONFIG_CAMERA_OV5647_AUTO_DETECT_MIPI_INTERFACE_SENSOR=y
CONFIG_CAMERA_OV5647_MIPI_RAW8_800X640_50FPS=y
CONFIG_CAMERA_OV5647_CSI_LINESYNC_ENABLE=y